name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - uses: actions/checkout@v3
      - name: Run Dagger pipeline
        run: go run build/main.go
